In [1]:
import pandas as pd

In [2]:
info = {
    "Name": ["Sarthak", "Harsh", "Ankur"],
    "CGPA": [8.5, 7.5, 9.5]
}
df = pd.DataFrame(info)
print(df)

      Name  CGPA
0  Sarthak   8.5
1    Harsh   7.5
2    Ankur   9.5

In [3]:
df

      Name  CGPA
0  Sarthak   8.5
1    Harsh   7.5
2    Ankur   9.5

In [4]:
s = pd.Series([1, 2, 3, 4, 5, 6])
print(s)
print(type(s))

# index
print(s[0])
print(s[2])

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
<class 'pandas.Series'>
1
3

In [5]:
s = pd.Series([23, 24, 25, 26], index=["Adam", "Bob", "Eve", "Charlie"])
print(s)
print(s["Adam"])
print(s.index)

Adam       23
Bob        24
Eve        25
Charlie    26
dtype: int64
23
Index(['Adam', 'Bob', 'Eve', 'Charlie'], dtype='str')

In [6]:
s1 = pd.Series([1, 2, 3, 4, 5, 6])
s2 = pd.Series([10, 11, 12, 13, 14, 15])

print(s1 + s2)

s1[0] = 100
changed_s1 = s1.drop(0)
print(s1)
print(changed_s1)

0    11
1    13
2    15
3    17
4    19
5    21
dtype: int64
0    100
1      2
2      3
3      4
4      5
5      6
dtype: int64
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [7]:
#Types of creating DataFrame

#Type1

info = {
    "Name": ["Adam", "Bob", "Eve"],
    "Age": [23, 26, 29],
    "GPA": [9.1, 9.2, 9.3]
}

df = pd.DataFrame(info)
print(df)
print(df.index)
print(df.columns)

   Name  Age  GPA
0  Adam   23  9.1
1   Bob   26  9.2
2   Eve   29  9.3
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'GPA'], dtype='str')

In [8]:
#Type2

df = pd.DataFrame([["Adam", 23], ["Bob", 24], ["Eve", 29]], columns = ["Name", "Age"])
print(df)

   Name  Age
0  Adam   23
1   Bob   24
2   Eve   29

In [9]:
#Type 3

import numpy as np

np_arr = np.array([[1, 2, 3], [4, 5, 6]])
df = pd.DataFrame(np_arr, columns= ["A", "B", "C"] )
print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [10]:
# csv data
df = pd.read_csv("employee_data.csv")
print(df)

#json data
# df = pd.read_json("employee_data.json")
# print(df)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [11]:
#Methods

df.head()  #first 5 rows

df.tail(2) #last 2 rows

df.sample()  #randomly one row

df.info()

df.shape

df.describe() #important numerical values

df.columns

df.nunique()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     str
 2   Age         10 non-null     int64
 3   Department  10 non-null     str
 4   Salary      10 non-null     int64
dtypes: int64(3), str(2)
memory usage: 628.0 bytes

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [12]:
#AQI Data Set

df = pd.read_csv("globalAirQuality.csv")

df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [13]:
# selecting columns

#columns
df["city"]
df[["city", "aqi"]]

#rows
df.loc[2]
df.loc[0:2] #start index : end index (inclusive)

df.iloc[2]
df.iloc[0:2] #start index : end index (exclusive)

#cells - row, columns
df.loc[0:2, "city"]
df.columns

df.loc[0:2, ["country", "city", "latitude", "longitude"]]
df.iloc[0:3, 1:5]

#cell
df.at[0, "city"]
df.iat[0, 2]

#copy
cities = df["city"].copy()
cities[0] = "Hello"

In [14]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [15]:
#Filtering of Data
df[ (df["aqi"] > 100) & (df["temperature"] > 30)]

aqi_data = df[ (df["aqi"] > 100) & (df["temperature"] > 30) ][["city", "aqi"]]
aqi_data.iloc[0]
aqi_data.loc[6]

#Query
aqi_value = 100
df.query("aqi > 100 & temperature > 30")[["city", "aqi"]]
df.query("aqi > @aqi_value & temperature > 30")[["city", "aqi"]]

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]

In [16]:
#Cleaning data - missing value
df = pd.read_csv("raw_data.csv")

df.isnull()
df.isna()

df.isnull().sum()

df.dropna() #delete missing value rows
df.dropna(axis = 1) #delete missing value columns

df.fillna(0)  #fill missing values with 0

age_mean = df["age"].mean()

cleaned_df = df.copy()
cleaned_df["age"] = cleaned_df["age"].fillna(age_mean)


df.ffill()  #forward fill -> replace null values with previous values
df.bfill()  #backward fill -> replace null values with next values

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [17]:
#Handle Duplicates

df.duplicated()
df2 = df.copy()
df2.drop_duplicates(inplace=True)

In [18]:
#Data Types
df.dtypes

df2 = df.copy()
df2 = df2.fillna(0)
df2["age"] = df2["age"].astype("int64")
df2.dtypes

df2["gender"].str.lower()
df2["gender"].str.upper()
df2["gender"].str.capitalize()

df2["name"].str.split(" ")
df2["country"].str.contains("india", case=False)

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object

In [19]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [20]:
aqi_data = pd.read_csv("globalAirQuality.csv")
aqi_data["timestamp"] = pd.to_datetime(aqi_data["timestamp"])
type(aqi_data["timestamp"].dtypes)

numpy.dtypes.DateTime64DType

In [21]:
data_str = pd.Series([pd.to_datetime("2026-12-31")])
type(data_str.dtypes)

numpy.dtypes.DateTime64DType

In [22]:
df2 = df.copy()
df2["tax"] = df["income"].apply(lambda x: "20%" if x >= 50000 else "10%")

gender_map = {"Male": "M", "Female": "F"}
df2["gender"] = df2["gender"].map(gender_map)

df2 = df2.assign(new_income = df2["income"]*1.1)

df2["country"] = df2["country"].replace("USA", "US")

df2.columns = df2.columns.str.capitalize()
df2.rename(columns={"Income": "Salary"})
df2.rename(index={1: "First"})

# map()      → map values according to a mapping
# replace()  → replace particular values
# apply()    → apply a function/logic
# assign()   → add/create a column
# rename()   → rename columns/index

df2 = df2.fillna(50)
# sorted_df = df2.sort_values("Income", ascending=False)
sorted_df = df2.sort_values(["Income", "Age"])

sorted_df.sort_index()

# reset
sorted_df.reset_index()
sorted_df.reset_index(drop=True)

# Ranking
sorted_df["Ranking"] = sorted_df["Income"].rank(ascending=False, method="dense") #method="min/max"
sorted_df

    Id          Name   Age Country Gender   Income  Tax  New_income  Ranking
4    4  Maria Garcia  34.0   Spain      F     50.0  10%        50.0      9.0
9    9   Carlos Ruiz  50.0  Mexico      M  45000.0  10%     49500.0      8.0
3    3          Alex  50.0      US     50  47000.0  10%     51700.0      7.0
5    5        Li Wei  27.0   China      M  51000.0  20%     56100.0      6.0
0    1      John Doe  29.0      US      M  55000.0  20%     60500.0      5.0
1    1      John Doe  29.0      US      M  55000.0  20%     60500.0      5.0
10  10   Emily Davis  31.0      US     50  58000.0  20%     63800.0      4.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0      3.0
2    2    Jane Smith  50.0  Canada      F  62000.0  20%     68200.0      3.0
7    7    Ahmed Khan  38.0      50      M  68000.0  20%     74800.0      2.0
6    6            50  45.0   India      F  73000.0  20%     80300.0      1.0

In [23]:
# Change columns order using list comprehensions

df2 = df.copy()

new_col_order = [col for col in df2.columns if col != "id"] + ["id"]

df2[new_col_order]

            name   age country   gender   income  id
0       John Doe  29.0     USA     Male  55000.0   1
1       John Doe  29.0     USA     Male  55000.0   1
2     Jane Smith   NaN  Canada   Female  62000.0   2
3           Alex   NaN     USA  Unknown  47000.0   3
4   Maria Garcia  34.0   Spain   Female      NaN   4
5         Li Wei  27.0   China     Male  51000.0   5
6            NaN  45.0   India   Female  73000.0   6
7     Ahmed Khan  38.0     NaN     Male  68000.0   7
8     Rachel Lee  29.0     USA   Female  62000.0   8
9    Carlos Ruiz   NaN  Mexico     Male  45000.0   9
10   Emily Davis  31.0     USA      NaN  58000.0  10

In [24]:
# Writing data to csv and json file

df2 = df.copy()

df2 = df2.drop_duplicates()

df2 = df2.fillna(0)

df2 = df2.sort_values("income")

df2 = df2.reset_index(drop=True)

df2.to_csv("sorted_data.csv")

In [32]:
# Group by & Aggregation

df2 = df.copy()

df2.groupby("country")["income"].mean()

df2.groupby("country")["income"].min()

df2.groupby('gender')["income"].mean()

df2.groupby("country")["income"].agg(["mean", "min", "max"]) #aggregate()

df2.groupby("country")["income"].agg(avg_salary="mean", min_salary="min", max_salary="max")

# df2.groupby("country").agg({
#     "income" : "max",
#     "age" : "mean"
# })

df2.groupby("country").agg(
    max_salary = ("income", "max"),
    avg_age = ("age", "mean")
    )

         max_salary  avg_age
country
Canada      62000.0      NaN
China       51000.0     27.0
India       73000.0     45.0
Mexico      45000.0      NaN
Spain           NaN     34.0
USA         62000.0     29.5